from pathlib import Path
import json
P=Path(r'F:\Vr\VR quirky testing gpt astra\League of legends test\league vr imoport testing');A=P/'Assets/_Game/LeagueVR/Champions/Art'
descriptions={
'Gwen':['Build snip stacks with hits; centre-line snips apply A Thousand Cuts.','Left primary: summon protective mist. Recast to move it once.','Right primary: a short collision-checked step; attacks gain speed and magic damage.','Left trigger: aim and fire three escalating needle volleys.'],
'Zoe':['Right secondary: launch a star. Press again within 1.25 seconds to redirect it. Distance increases damage.','Collect glowing shards from fallen minions with your left hand or nearby W. W uses Heal, Flash or Ignite and launches three missiles.','Right primary: toss a bubble. The hit slows, then sleeps. Your next hit wakes it for bonus damage.','Left trigger: aim at ground. Blink through a portal for one second, then return. Tracking orientation stays yours.'],
'Aatrox':['Right secondary: three aimed sword slams. Press again for the next shape. Sweet spots knock enemies off balance.','Aim your left hand and press left primary to launch chains. Enemies that stay inside are pulled back.','Right primary: a collision-checked short step that resets your attack timer.','Left trigger: enter World Ender for ten seconds. Gain speed, empowered attacks and stronger champion healing.'],
'Akshan':['Right secondary: throw a piercing boomerang that comes back to your hand.','Left primary: camouflage for six seconds. Close champions and turrets reveal you. Scoundrel takedowns revive allied champions.','Aim the right hand at terrain, then right primary. Grapple-step toward the anchor with a short shot; no forced orbit.','Aim at an enemy with the left hand and press trigger. Charge, then fire five interceptable homing shots.'],
'Brand':['Right secondary: fire a bolt. Targets already burning are stunned.','Aim left hand at ground and press left primary. A delayed flame pillar hits harder against burning targets.','Aim right hand at an enemy and press right primary. Fire spreads; burning targets spread it further.','Left trigger: select an enemy for five bouncing fire hits. It may bounce through you without hurting you.'],
'Pantheon':['Right secondary: throw your spear. Five Mortal Will stacks empower it. Low-health enemies take extra damage.','Aim left hand at a nearby enemy and press left primary. Step into range and stun them; empowered vault adds three hits.','Right primary: raise Aegis Assault. Point the left shield toward incoming damage while your spear strikes. Turrets still hurt.','Left trigger: aim at ground up to 24 metres. A one-second landing warning, then a comfortable blink and impact.'],
'Yunara':['Land eight basic attacks for Spirit stacks. Right secondary spends them to gain attack speed and splash hits.','Left primary: aim a slowing bead. During Transcendence it becomes a piercing beam.','Right primary: speed burst. During Transcendence it becomes a collision-checked short dash.','Left trigger: Transcend for twelve seconds. Q stays active, W becomes a beam, and E becomes a dash.']}
colors=[[.3,.9,.94],[.76,.39,1],[.94,.16,.21],[1,.73,.25],[1,.35,.09],[.9,.79,.47],[.45,.91,.65]]
passives=['A Thousand Cuts applies bonus max-health magic damage.','Casting empowers the next attack with More Sparkles.','Deathbringer hits heal; E heals on champion damage.','Three hits proc bonus damage and a champion shield; attacks fire twice.','Spells stack a four-second burn; three stacks detonate champions and large monsters.','Five attacks or spells empower the next basic ability.','Critical strikes deal bonus magic damage.']
records=[]
for i,name in enumerate(descriptions):
 d=json.loads((A/name/(name+'.json')).read_text(encoding='utf-8'))['data'][name];st=d['stats'];r={'id':i,'name':name,'title':d['title'],'role':' / '.join(d['tags']),'passiveName':d['passive']['name'],'passiveDescription':passives[i],'patch':json.loads((P/'Logs/ChampionExpansion/Sources.json').read_text())['patch'],'color':{'r':colors[i][0],'g':colors[i][1],'b':colors[i][2],'a':1},'portrait':name+'.png','passiveIcon':d['passive']['image']['full'],'attackReach':2.4 if name in ['Gwen','Aatrox','Pantheon'] else 10,'spells':[]}
 for field,key in [('health','hp'),('healthGrowth','hpperlevel'),('armor','armor'),('armorGrowth','armorperlevel'),('magicResist','spellblock'),('magicResistGrowth','spellblockperlevel'),('mana','mp'),('manaGrowth','mpperlevel'),('attackDamage','attackdamage'),('attackGrowth','attackdamageperlevel'),('attackSpeed','attackspeed'),('attackSpeedGrowth','attackspeedperlevel'),('moveSpeed','movespeed'),('healthRegen','hpregen'),('manaRegen','mpregen')]:r[field]=st[key]
 for n,x in enumerate(d['spells']):r['spells'].append({'name':x['name'],'vrDescription':descriptions[name][n],'icon':x['image']['full'],'cooldowns':x['cooldown'],'costs':x['cost']})
 records.append(r)
(P/'Assets/_Game/LeagueVR/Champions/RosterSource.json').write_text(json.dumps({'champions':records},indent=2),encoding='utf-8')
print('Roster source written')
