using System;using System.IO;using System.Linq;using System.Text;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using LeagueVR.Match;using Object=UnityEngine.Object;
namespace LeagueVR.Editor{
 public static class LeagueVRPresentationBuild{
  const string Root="Assets/_Game/LeagueVR/Match";const string AudioRoot="Assets/_Game/LeagueVR/Audio/OriginalLeague";
  [Serializable]class Manifest{public Entry[] events;}[Serializable]class Entry{public string key,eventName,bank;public Layer[] layers;}[Serializable]class Layer{public string[] clips;}
  public static void Apply(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");var match=Object.FindAnyObjectByType<RiftMatch>();if(!match)throw new Exception("Open LeagueVR scene");Directory.CreateDirectory("Logs/Presentation");Directory.CreateDirectory(Root+"/Generated/OriginalAnimationClips");Directory.CreateDirectory("PrototypeBackups/OriginalPresentationPrefabs");
   var report=new StringBuilder();var bank=AssetDatabase.LoadAssetAtPath<LeagueSoundBank>(AudioRoot+"/Original League Sounds.asset");if(!bank){bank=ScriptableObject.CreateInstance<LeagueSoundBank>();AssetDatabase.CreateAsset(bank,AudioRoot+"/Original League Sounds.asset");}var manifest=JsonUtility.FromJson<Manifest>(File.ReadAllText(AudioRoot+"/sound-manifest.json"));bank.events=manifest.events.Select(e=>new LeagueSoundBank.Event{key=e.key,eventName=e.eventName,sourceBank=e.bank,layers=e.layers.Select(l=>new LeagueSoundBank.Layer{variants=l.clips.Select(p=>AssetDatabase.LoadAssetAtPath<AudioClip>(AudioRoot+"/"+p)??throw new Exception("Missing audio "+p)).ToArray()}).ToArray()}).ToArray();bank.outputGain=.6f;EditorUtility.SetDirty(bank);
   // Audio remains original decoded media. Decompress short effects to avoid decoder startup at VR cast time.
   foreach(var path in manifest.events.SelectMany(e=>e.layers).SelectMany(l=>l.clips).Distinct()){var imp=AssetImporter.GetAtPath(AudioRoot+"/"+path) as AudioImporter;if(imp==null)continue;var settings=imp.defaultSampleSettings;settings.loadType=AudioClipLoadType.DecompressOnLoad;settings.compressionFormat=AudioCompressionFormat.PCM;settings.preloadAudioData=true;imp.defaultSampleSettings=settings;imp.SaveAndReimport();}
   string[] units={"sru_orderminionmelee","sru_orderminionranged","sru_orderminionsiege","sru_orderminionsuper"};float[] scales={.007f,.0076f,.00925f,.0105f};string[] textures={"orderminion_melee_tx_cm","orderminion_caster_tx_cm","order_minion_siege_tx_cm","blue_superminion_tx_cm"};
   for(int i=0;i<match.minions.Length;i++){var prefab=match.minions[i];string path=AssetDatabase.GetAssetPath(prefab);string backup="PrototypeBackups/OriginalPresentationPrefabs/"+Path.GetFileName(path);if(!File.Exists(backup))File.Copy(path,backup);int type=i%4,team=i/4;string modelPath=Root+"/Art/OriginalAnimations/"+units[type]+".glb";var source=AssetDatabase.LoadAssetAtPath<GameObject>(modelPath);if(!source)throw new Exception("Model not imported: "+modelPath);
    var clips=AssetDatabase.LoadAllAssetsAtPath(modelPath).OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview")).Select(c=>Legacy(c,units[type])).ToArray();if(clips.Length<4)throw new Exception("Missing original clips "+modelPath);var go=PrefabUtility.LoadPrefabContents(path);try{var minion=go.GetComponent<RiftMinion>();if(minion.visual)Object.DestroyImmediate(minion.visual.gameObject);var model=Object.Instantiate(source,go.transform);model.name="Original animated League minion";model.transform.localPosition=Vector3.zero;model.transform.localRotation=Quaternion.identity;model.transform.localScale=Vector3.one*scales[type];foreach(var a in model.GetComponentsInChildren<Animator>())Object.DestroyImmediate(a);foreach(var a in model.GetComponentsInChildren<Animation>())Object.DestroyImmediate(a);var anim=model.AddComponent<Animation>();anim.playAutomatically=false;anim.cullingType=AnimationCullingType.AlwaysAnimate;foreach(var clip in clips)anim.AddClip(clip,clip.name);var motion=model.AddComponent<RiftMinionMotion>();motion.player=anim;motion.idle=clips.First(c=>c.name.Contains("idle")).name;motion.run=clips.First(c=>c.name.Contains("run")).name;motion.attacks=clips.Where(c=>c.name.Contains("attack")).Select(c=>c.name).OrderBy(n=>n).ToArray();motion.deaths=clips.Where(c=>c.name.Contains("death")).Select(c=>c.name).ToArray();ConfigureBindings(motion,type);motion.corpseLifetime=4;motion.fadeDuration=.65f;motion.releaseFraction=type==0?7f/27f:.3f;anim.clip=clips.First(c=>c.name==motion.idle);anim.wrapMode=WrapMode.Loop;
     string materialPath=Root+"/Generated/Original "+prefab.name+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(materialPath);if(!mat){mat=new Material(Shader.Find("Universal Render Pipeline/Unlit"));AssetDatabase.CreateAsset(mat,materialPath);}var texture=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/Art/Models/"+units[type]+"/"+textures[type]+(team==1?"_red":"")+".png");if(!texture)throw new Exception("Missing original texture");mat.SetTexture("_BaseMap",texture);mat.SetTextureScale("_BaseMap",Vector2.one);mat.SetTextureOffset("_BaseMap",Vector2.zero);mat.SetColor("_BaseColor",Color.white);mat.SetFloat("_Cull",0);mat.SetFloat("_Surface",0);mat.SetFloat("_Blend",0);mat.SetFloat("_SrcBlend",1);mat.SetFloat("_DstBlend",0);mat.SetFloat("_SrcBlendAlpha",1);mat.SetFloat("_DstBlendAlpha",0);mat.SetFloat("_ZWrite",1);mat.DisableKeyword("_SURFACE_TYPE_TRANSPARENT");mat.SetOverrideTag("RenderType","Opaque");mat.SetShaderPassEnabled("DepthOnly",true);mat.renderQueue=2000;EditorUtility.SetDirty(mat);
     foreach(var skin in model.GetComponentsInChildren<SkinnedMeshRenderer>()){skin.sharedMaterials=Enumerable.Repeat(mat,skin.sharedMaterials.Length).ToArray();skin.updateWhenOffscreen=true;skin.localBounds=new Bounds(Vector3.up*70,new Vector3(500,400,500));skin.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;report.AppendLine(prefab.name+" bones="+skin.bones.Length+" mesh="+skin.sharedMesh.name+" texture="+texture.name);}
     minion.visual=model.transform;var ua=go.GetComponent<LeagueUnitAudio>();if(!ua)ua=go.AddComponent<LeagueUnitAudio>();ua.bank=bank;ua.volume=.24f;PrefabUtility.SaveAsPrefabAsset(go,path);report.AppendLine(prefab.name+" clips="+clips.Length+" scale="+scales[type]+" deaths="+string.Join(",",motion.deaths));
    }finally{PrefabUtility.UnloadPrefabContents(go);}}
   // Pad centres come from the original source terrain boundary loops and an orthographic pixel/world calibration, never the current seasonal map.
   Vector2[][][] pads={new[]{new[]{new Vector2(-65.0396f,36.1825f),new Vector2(-59.9914f,-.1094f),new Vector2(-62.8281f,-22.8638f),new Vector2(-62.8012f,-29.8255f)},new[]{new Vector2(-17.2488f,-3.062f),new Vector2(-25.3645f,-18.3329f),new Vector2(-38.4769f,-29.0145f),new Vector2(-43.0216f,-33.4264f)},new[]{new Vector2(27.5998f,-54.9168f),new Vector2(-7.6282f,-50.0523f),new Vector2(-32.2123f,-52.7881f),new Vector2(-39.8003f,-52.8561f)}},new[]{new[]{new Vector2(-32.62f,70.0f),new Vector2(2.4f,65.63f),new Vector2(27.70f,67.8253f),new Vector2(35.764f,68.0391f)},new[]{new Vector2(12.72f,17.89f),new Vector2(20.66f,33.32f),new Vector2(33.9199f,43.8746f),new Vector2(38.32f,48.69f)},new[]{new Vector2(60.43f,-21.14f),new Vector2(55.31f,15.18f),new Vector2(58.332f,38.0529f),new Vector2(58.1458f,44.9272f)}}};
   for(int team=0;team<2;team++){var list=match.structures.Where(s=>s.health.team==team).ToArray();foreach(var s in list){Vector2 p;float yaw; if(s.lane>=0){int stage=s.kind==StructureKind.Inhibitor?3:(int)s.kind;p=pads[team][s.lane][stage];yaw=s.lane==0?(team==0?0:270):s.lane==2?(team==0?90:180):team==0?45:225;}else if(s.kind==StructureKind.Nexus){p=team==0?new Vector2(-59.3111f,-48.6239f):new Vector2(54.493f,63.9141f);yaw=team==0?45:225;}else{int n=Array.IndexOf(list.Where(t=>t.kind==StructureKind.NexusTurret).ToArray(),s);p=team==0?(n==0?new Vector2(-57.2333f,-42.7121f):new Vector2(-52.9224f,-47.4306f)):(n==0?new Vector2(48.29f,62.52f):new Vector2(52.0f,57.98f));yaw=team==0?45:225;}
     Vector3 before=s.transform.position;var at=new Vector3(p.x,team==0?.4533f:.4953f,p.y);if(!match.Ground(at,out var ground))throw new Exception("No pad ground "+s.name);s.transform.SetPositionAndRotation(ground,Quaternion.Euler(0,yaw,0));s.visual.localRotation=Quaternion.Euler(0,s.kind==StructureKind.Inhibitor||s.kind==StructureKind.Nexus?0:90,0);var audio=s.GetComponent<LeagueUnitAudio>();if(!audio)audio=s.gameObject.AddComponent<LeagueUnitAudio>();audio.bank=bank;audio.volume=.7f;EditorUtility.SetDirty(s);report.AppendLine(s.name+" "+before+" -> "+ground+" yaw="+yaw);}}
   var gwen=match.player.GetComponent<GwenAudio>();gwen.originalSounds=bank;gwen.scissors=gwen.snip=gwen.mist=gwen.dash=gwen.needle=gwen.impact=gwen.hurt=gwen.footstep=gwen.ambience=null;gwen.effectsVolume=.8f;gwen.ambienceVolume=0;EditorUtility.SetDirty(gwen);AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(match.gameObject.scene);EditorSceneManager.SaveScene(match.gameObject.scene);report.AppendLine("Verified original audio events "+bank.events.Length);File.WriteAllText("Logs/Presentation/Applied.txt",report.ToString());LeagueVRPresentationWork.CaptureOverview("Corrected",false);Debug.Log("Original minion animations, original audio, and structure pad alignment saved.");
  }
  static void ConfigureBindings(RiftMinionMotion m,int type){m.magicDeath=type==0?"minion_melee_death4":type==1?"minion_caster_death2":"";m.deaths=type==0?new[]{"minion_melee_death"}:type==1?new[]{"minion_caster_death3"}:type==2?new[]{"cannon_order_death1"}:new[]{"superminion_blue_death","superminion_blue_death2"};m.attackWeights=type==2?new[]{.4f,.3f,.3f}:null;}
  // The imported turret statue faces -X; +90 degrees makes its chest face the lane root's +Z.
  public static void Facing(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");var match=Object.FindAnyObjectByType<RiftMatch>();foreach(var s in match.structures){s.visual.localRotation=Quaternion.Euler(0,s.kind==StructureKind.Inhibitor||s.kind==StructureKind.Nexus?0:90,0);EditorUtility.SetDirty(s.visual);}EditorSceneManager.MarkSceneDirty(match.gameObject.scene);EditorSceneManager.SaveScene(match.gameObject.scene);LeagueVRPresentationWork.CaptureOverview("Corrected",false);}
  public static void Bindings(){var match=Object.FindAnyObjectByType<RiftMatch>();for(int i=0;i<match.minions.Length;i++){string path=AssetDatabase.GetAssetPath(match.minions[i]);var go=PrefabUtility.LoadPrefabContents(path);try{var m=go.GetComponentInChildren<RiftMinionMotion>();m.attacks=m.player.Cast<AnimationState>().Where(a=>a.name.Contains("attack")).Select(a=>a.name).OrderBy(n=>n).ToArray();ConfigureBindings(m,i%4);PrefabUtility.SaveAsPrefabAsset(go,path);}finally{PrefabUtility.UnloadPrefabContents(go);}}AssetDatabase.SaveAssets();}
  static AnimationClip Legacy(AnimationClip source,string unit){string dir=Root+"/Generated/OriginalAnimationClips/"+unit;Directory.CreateDirectory(dir);string path=dir+"/"+source.name+".anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(path);if(clip)return clip;clip=Object.Instantiate(source);clip.name=source.name;clip.legacy=true;clip.wrapMode=source.name.Contains("idle")||source.name.Contains("run")?WrapMode.Loop:WrapMode.ClampForever;AssetDatabase.CreateAsset(clip,path);return clip;}
 }
}

