using System;using System.IO;using System.Linq;using System.Text;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.Rendering.Universal;using LeagueVR.Match;using Object=UnityEngine.Object;
namespace LeagueVR.Editor{
[InitializeOnLoad]public static class LeagueVRPresentationWork{
 static double next;static LeagueVRPresentationWork(){EditorApplication.update+=Tick;}
 static void Tick(){if(EditorApplication.timeSinceStartup<next||EditorApplication.isCompiling||EditorApplication.isUpdating)return;next=EditorApplication.timeSinceStartup+1;const string p="Temp/LeagueVRPresentation.request";if(!File.Exists(p))return;string action=File.ReadAllText(p).Trim();File.Delete(p);Directory.CreateDirectory("Logs/Presentation");try{if(action=="Baseline")Baseline();else if(action=="MinionFix")LeagueVRMinionCheck.ApplyAndBegin();else if(action=="Facing")LeagueVRPresentationBuild.Facing();else if(action=="Bindings")LeagueVRPresentationBuild.Bindings();else if(action=="Mix"){var bank=Object.FindAnyObjectByType<RiftMatch>().player.GetComponent<GwenAudio>().originalSounds;bank.outputGain=.6f;EditorUtility.SetDirty(bank);AssetDatabase.SaveAssets();}else if(action=="Apply")LeagueVRPresentationBuild.Apply();else if(action.StartsWith("Test"))LeagueVRPresentationTest.Begin(action);else if(action=="FinalViews")LeagueVRPresentationTest.Audit(action);else if(action=="VisualAudit")LeagueVRPresentationTest.Audit("VisualAudit");else throw new Exception("Unknown action "+action);}catch(Exception e){File.WriteAllText("Logs/Presentation/error.txt",e.ToString());Debug.LogException(e);}}
 static void Baseline(){if(EditorApplication.isPlaying)throw new Exception("Edit mode required");EditorSceneManager.SaveScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene(),"PrototypeBackups/"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-BeforeOriginalPresentation.unity",true);var m=Object.FindAnyObjectByType<RiftMatch>();var b=new StringBuilder();b.AppendLine("BASELINE "+DateTime.Now);foreach(var s in m.structures)b.AppendLine(s.name+" "+s.transform.position+" yaw="+s.transform.eulerAngles.y+" visual="+s.visual.localEulerAngles);foreach(var p in m.minions)b.AppendLine(p.name+" skinned="+p.GetComponentsInChildren<SkinnedMeshRenderer>(true).Length+" clips="+p.GetComponentsInChildren<Animation>(true).Length);var a=m.player.GetComponent<GwenAudio>();b.AppendLine("Gwen audio "+string.Join(",",new[]{a.scissors,a.snip,a.mist,a.dash,a.needle,a.impact,a.hurt,a.footstep,a.ambience}.Where(c=>c).Select(AssetDatabase.GetAssetPath)));File.WriteAllText("Logs/Presentation/Baseline.txt",b.ToString());CaptureOverview("Baseline",false);CaptureOverview("BareMap",true);}
 public static void CaptureOverview(string name,bool hide){var m=Object.FindAnyObjectByType<RiftMatch>();var rs=m.structures.SelectMany(s=>s.GetComponentsInChildren<Renderer>()).ToArray();var en=rs.Select(r=>r.enabled).ToArray();var go=new GameObject("Temporary overview"){hideFlags=HideFlags.HideAndDontSave};var c=go.AddComponent<Camera>();c.enabled=false;c.GetUniversalAdditionalCameraData().allowXRRendering=false;c.orthographic=true;c.orthographicSize=87;c.farClipPlane=500;c.transform.SetPositionAndRotation(new Vector3(0,200,8),Quaternion.Euler(90,0,0));c.cullingMask=~(1<<LayerMask.NameToLayer("UI"));var rt=new RenderTexture(2048,2048,24);c.targetTexture=rt;bool fog=RenderSettings.fog;try{RenderSettings.fog=false;if(hide)foreach(var r in rs)r.enabled=false;LeagueVRMapWork.Capture(c,rt,"Logs/Presentation/"+name+".png");}finally{for(int i=0;i<rs.Length;i++)rs[i].enabled=en[i];RenderSettings.fog=fog;c.targetTexture=null;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(go);}}
}}



