using System.Collections.Generic;using UnityEngine;
namespace LeagueVR.Match{
 public class RiftMinionMotion:MonoBehaviour{
  public Animation player;public string idle,run;public string[] attacks,deaths;public string magicDeath;public float[] attackWeights;public float corpseLifetime=4,fadeDuration=.65f,releaseFraction=.3f;public int AttackVariant{get;private set;}public string State{get;private set;}public float CorpseExpires{get;private set;}
  float actionUntil,deadAt=-1;int sequence;Renderer[] renderers;MaterialPropertyBlock block;bool fading;readonly List<Material> temporaryMaterials=new List<Material>();
  void Awake(){renderers=GetComponentsInChildren<Renderer>();block=new MaterialPropertyBlock();if(player){player.playAutomatically=false;player.cullingType=AnimationCullingType.AlwaysAnimate;player.Stop();Locomotion(false);}}
  public void Locomotion(bool moving){if(!player||deadAt>=0||Time.time<actionUntil)return;string clip=moving?run:idle;if(player[clip]==null)return;if(State==clip&&player.IsPlaying(clip))return;player[clip].speed=1;player[clip].wrapMode=WrapMode.Loop;player.CrossFade(clip,.10f);State=clip;}
  public float Attack(float interval){if(!player||deadAt>=0||attacks.Length==0)return interval*releaseFraction;int count=attacks.Length;if(count==4&&attacks[3].EndsWith("3b"))count=3;AttackVariant=sequence++%count;if(attackWeights!=null&&attackWeights.Length==count){float roll=Random.value;for(int i=0;i<count;i++){roll-=attackWeights[i];if(roll<=0){AttackVariant=i;break;}}}string clip=count==3&&attacks.Length==4&&AttackVariant==2&&Random.value<.5f?attacks[3]:attacks[AttackVariant];var state=player[clip];if(state==null)return interval*releaseFraction;player.Stop();state.time=0;state.speed=state.length/Mathf.Max(.1f,interval);state.wrapMode=WrapMode.ClampForever;player.Play(clip);actionUntil=Time.time+interval;State=clip;return interval*releaseFraction;}
  public void Die(bool magic=false){if(deadAt>=0)return;deadAt=Time.time;float length=0;if(player&&deaths.Length>0){string clip=magic&&!string.IsNullOrEmpty(magicDeath)?magicDeath:deaths[Random.Range(0,deaths.Length)];var s=player[clip];if(s!=null){player.Stop();s.time=0;s.speed=1;s.wrapMode=WrapMode.ClampForever;player.Play(clip);State=clip;length=s.length;}}CorpseExpires=deadAt+Mathf.Max(corpseLifetime,length+fadeDuration);}
  // Living units and the death animation remain opaque. Only the final dissolve needs blending.
  void BeginFade(){fading=true;var copies=new Dictionary<Material,Material>();foreach(var r in renderers){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++){var original=mats[i];if(!original)continue;if(!copies.TryGetValue(original,out var fade)){fade=new Material(original){name=original.name+" corpse fade"};fade.SetFloat("_Surface",1);fade.SetFloat("_SrcBlend",5);fade.SetFloat("_DstBlend",10);fade.SetFloat("_SrcBlendAlpha",1);fade.SetFloat("_DstBlendAlpha",10);fade.SetFloat("_ZWrite",1);fade.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");fade.SetOverrideTag("RenderType","Transparent");fade.renderQueue=3000;copies.Add(original,fade);temporaryMaterials.Add(fade);}mats[i]=fade;}r.sharedMaterials=mats;}}
  void OnDestroy(){foreach(var mat in temporaryMaterials)if(mat)Destroy(mat);}
  void Update(){if(deadAt<0)return;float alpha=Mathf.Clamp01((CorpseExpires-Time.time)/Mathf.Max(.01f,fadeDuration));if(alpha<1&&!fading)BeginFade();foreach(var r in renderers){r.GetPropertyBlock(block);block.SetColor("_BaseColor",new Color(1,1,1,alpha));r.SetPropertyBlock(block);}if(Time.time>=CorpseExpires)Destroy(GetComponentInParent<RiftMinion>().gameObject);}
 }
}
